version: '3.5'

services:
  suits-auth:
    image: suitsims/suits-auth:1.0.1
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin